### ISSUE TITLE
Refreshing a results page keeps some info but not others, and doesn't show info

### ISSUE THREAD

**Issue by odscjames** [IATI/datastore-search#612]
**Brief Description**
Refreshing a results page keeps some info but not others

**Severity**
Medium

**Issue Location**
https://datastore.iatistandard.org/

**Steps to Reproduce**
1. Open advanced search
2. Search for an OR condition - eg Sector code = Example1 OR Sector code = Example2
3. Hit refresh

**Expected Results/Behaviour**
Stay on results page, do exact same search

**Actual Results/Behaviour**
You go back to the front page.

If you open advanced search then you get the sector codes remembered and still in the form - but not OR! It's gone back to AND.

**Comment by IsabelBirds** [comment]
+1, also encountering this issue in firefox. This also occurs when importing a query, making this an error that affects us when sharing queries through the support desk. I have to instruct people to change the query I am sharing with them.

**Comment by IsabelBirds** [comment]
Looks good to me - rerunning a search keeps the current AND/ORs, as does importing/exporting a query.
Thanks!
